name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        laravel: ['10.*', '11.*', '12.*','13.*']
        exclude:
          - php: '8.1'
            laravel: '11.*'
          - php: '8.1'
            laravel: '12.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_mysql, zip, zlib
          coverage: none

      - name: Instalar cliente MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Instalar dependencias
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --with-all-dependencies

      - name: Testes
        run: vendor/bin/phpunit
        env:
          BACKUP_TEST_DB_PASSWORD: root

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
      - run: composer update --prefer-dist --no-interaction
      - run: vendor/bin/pint --test
      - run: vendor/bin/phpstan analyse --memory-limit=1G --no-progress
